Repository FastCampusKDTBackend-Toy4/KDT_Y_BE_Toy_Project2, pull requests merged in 2023-11, with the labels that each got.

#81 회원 엔티티 생성
  src/main/java/com/kdt_y_be_toy_project2/domain/member/domain/Member.java
  src/main/java/com/kdt_y_be_toy_project2/domain/member/repository/MemberRepository.java
Labels: feat

#84 [fix] 국내외여부 enum 변환 클래스에 `@Converter` 주석 추가
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripTypeConverter.java
Labels: fix

#82 `docker-compose` 수정
  .env.example
  docker-compose.yml
Labels: fix

#90 컨트롤러 유닛 테스트 헬퍼 추가
  src/test/java/com/kdt_y_be_toy_project2/global/helper/ControllerUnitTestHelper.java
Labels: feat

#94 1. 여정 Entity에 NotNull 추가, 2. 서비스 중복 로직 모듈화
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/Itinerary.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryControllerTest.java
Labels: refactor

#97 [feat] Jwt 인증 추가
  src/main/java/com/kdt_y_be_toy_project2/global/config/CustomHttpHeaders.java
  src/main/java/com/kdt_y_be_toy_project2/global/jwt/JwtProvider.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtPair.java
Labels: feat

#100 [feat] FormLogin 추가
  src/main/java/com/kdt_y_be_toy_project2/global/security/SecurityConfig.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/SecurityFilterConfig.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/login/AccountContext.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/login/CustomUserDetailsService.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/login/CustomUsernamePasswordAuthenticationSuccessHandler.java
Labels: feat

#103 [refactor] FormLogin 재등록
  src/main/java/com/kdt_y_be_toy_project2/domain/member/controller/MemberController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/member/service/MemberService.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/SecurityConfig.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/SecurityFilterConfig.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/formlogin/AccountContext.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/formlogin/CustomFormLoginFilter.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/formlogin/CustomFormLoginProvider.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/formlogin/CustomLoginToken.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/formlogin/CustomUserDetailsService.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationFilter.java
Labels: refactor

#105 [feat] SecurityContextHolder 데이터를 추출할 ArgumentResolver 추가
  src/main/java/com/kdt_y_be_toy_project2/global/config/WebMvcConfig.java
  src/main/java/com/kdt_y_be_toy_project2/global/resolver/LoginInfo.java
  src/main/java/com/kdt_y_be_toy_project2/global/resolver/LoginInfoArgumentResolver.java
  src/main/java/com/kdt_y_be_toy_project2/global/resolver/SecurityContext.java
Labels: feat

#96 여행 검색 기능 추가
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripSearchRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/exception/TripSearchIllegalArgumentException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/repository/TripRepository.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
Labels: feat

#106 좋아요 기능 추가
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Likes.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/id/LikesID.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/exception/TripAlreadyLikesException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/repository/LikesRepository.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
Labels: feat

#109 여행에 멤버 권한 추가
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/TransportationType.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/TransportationTypeConverter.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripType.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/type/TripType.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/type/TripTypeConverter.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripSearchRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/repository/TripRepository.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/service/TripServiceTest.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/MemberTestFactory.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java
Labels: feat

#112 여행 통합 테스트에 jwt token 추가 및 layer별 유닛 테스트 작성
  src/main/resources/application.yaml
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryIntegrationTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/repository/ItineraryRepositoryTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryServiceTest.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/ItineraryTestFactory.java
Labels: test

#113 여정 수정, 생성 시 권한 검증 로직 추가 및 통합 테스트 코드 수정
  gradlew
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/Itinerary.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/InvalidAuthException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
  src/main/resources/application.yaml
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryIntegrationTest.java
Labels: feat, test

#108 OpenAPI를 이용하여 PlaceInfo 정보 고도화
  .env.example
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/api/RoadAddressInfoAPI.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/AccommodationInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/MoveInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/StayInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/response/AccommodationInfoResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/response/MoveInfoResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/response/StayInfoResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/ApiConnectionException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
  src/main/java/com/kdt_y_be_toy_project2/domain/model/PlaceInfo.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
  src/main/resources/application.yaml
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryIntegrationTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/repository/ItineraryRepositoryTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryServiceTest.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java
Labels: feat

#118 [refactor] JwtFilter 의존성 변경
  src/main/java/com/kdt_y_be_toy_project2/global/security/formlogin/CustomFormLoginFilter.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/kdt_y_be_toy_project2/global/security/jwt/JwtAuthenticationToken.java
Labels: refactor

#126 MemberNotFoundException 추가
  src/main/java/com/kdt_y_be_toy_project2/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
Labels: feat

#128 예외 처리 리팩토링 및 여행 등록 및 수정 시 예외 기능 추가
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/InvalidAuthException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/InvalidDateException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/InvalidItineraryDateException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/exception/TripNotFoundException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
  src/main/java/com/kdt_y_be_toy_project2/domain/member/exception/InvalidAuthException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryIntegrationTest.java
Labels: feat, refactor

#130 댓글 기능을 제외한 레이어별 여행 유닛 테스트를 개발한다.
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Likes.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripIntegrationTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/repository/TripRepositoryTest.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java
  src/test/java/com/kdt_y_be_toy_project2/integration/TripAndItineraryIntegrationTest.java
Labels: test

#136 댓글 관련 엔티티 수정
  src/main/java/com/kdt_y_be_toy_project2/domain/member/domain/Member.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Comment.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
Labels: fix

#138 URL 권한 설정
  src/main/java/com/kdt_y_be_toy_project2/global/security/SecurityFilterConfig.java
Labels: feat

#139 여행 컨트롤러에 스웨거 관련 주석 작성
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
Labels: docs

#142 여행 댓글 등록, 조회 테스트
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/service/TripServiceTest.java
Labels: test

#144 유닛, 통합 테스트 오류 수정
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripIntegrationTest.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/service/TripServiceTest.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/MemberTestFactory.java
Labels: fix, test
