Repository FastCampusKDTBackend-Toy4/KDT_Y_BE_Toy_Project2, pull requests merged in 2023-10, with the labels that each got.

#5 [feat] docker-compose.yml 등록을 한다.
  .gitignore
  docker-compose.yml
Labels: feat

#9 [feat] 여행 엔티티 개발
  src/main/java/com/kdt_y_be_toy_project2/domain/model/TimeScheduleInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/.gitkeep
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripType.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/repository/.gitkeep
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/repository/TripRepository.java
Labels: feat

#14 [refactor] `application.properties` 수정
  src/main/resources/application-dev.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
Labels: refactor

#19 Feature/Global Exception Handler 추가
  src/main/java/com/kdt_y_be_toy_project2/global/error/.gitkeep
  src/main/java/com/kdt_y_be_toy_project2/global/error/ApplicationException.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorResponse.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/GlobalExceptionHandler.java
Labels: feat

#22 [feat] 여행 컨트롤러와 서비스, DTO를 개발한다.
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/.gitkeep
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/.gitkeep
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/CreateTripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/CreateTripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/EditTripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/EditTripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/GetTripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/exception/.gitkeep
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/exception/TripNotFoundException.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/repository/TripRepository.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/.gitkeep
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
Labels: feat

#28 [feat] open api 문서 적용
  build.gradle
  src/main/java/com/kdt_y_be_toy_project2/global/config/OpenApi3Config.java
Labels: docs, feat

#31 [feat] 여행 도메인에 여정 리스트 추가 관련 개발
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/Itinerary.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/CreateTripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/EditTripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/EditTripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
Labels: fix, feat, refactor

#39 [feat] 공통 유틸리티 클래스 추가
  src/main/java/com/kdt_y_be_toy_project2/global/util/DateTimeUtil.java
Labels: feat

#47 [fix] `ErrorCode` Compile Error 수정
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
Labels: fix

#43 [refactor] TripRequest에 공통 유틸리티 클래스 적용
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/global/util/DateTimeUtil.java
Labels: refactor

#53 [feat] 여행 검증 및 예외처리
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/AccommodationInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/MoveInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/StayInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/AccommodationInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/MoveInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/StayInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
  src/main/java/com/kdt_y_be_toy_project2/domain/model/DateScheduleInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/model/DateTimeScheduleInfo.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/test/java/com/kdt_y_be_toy_project2/domain/model/DateTimeScheduleInfoTest.java
Labels: feat

#52 [refactor] Trip Entity 수정
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/resources/application.yaml
Labels: refactor

#51 [feat] TripType.java에 한글 value 추가
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripType.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/TripTypeConverter.java
Labels: feat

#59 [fix] 여행 도메인의 DTO의 TripType 수정
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
Labels: fix

#60 [test] 여행 컨트롤러 통합 테스트 성공 케이스 작성
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/DateScheduleInfoTestFactory.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java
Labels: test

#63 [docs] 여행 API Swagger 문서화
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
  src/main/java/com/kdt_y_be_toy_project2/global/config/.gitkeep
  src/main/java/com/kdt_y_be_toy_project2/global/config/OpenApi3Config.java
Labels: docs

#65 [test] 여행 서비스 유닛 테스트 코드 작성
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/service/TripService.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/service/TripServiceTest.java
Labels: test

#67 [fix] 여행 조회 시 무한 순환 참조 문제
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/dto/TripResponse.java
Labels: fix

#71 [test, feat] 여행 도메인 통합 테스트(실패케이스) 작성 및 바인딩 핸들러 추가
  src/main/java/com/kdt_y_be_toy_project2/global/error/GlobalExceptionHandler.java
  src/test/java/com/kdt_y_be_toy_project2/domain/trip/controller/TripControllerTest.java
Labels: feat, test

#56 [feat, test, docs] 여정 관련 통합 테스트 코드 작성
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/Itinerary.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/TransportationType.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/domain/TransportationTypeConverter.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/AccommodationInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/ItineraryRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/ItineraryResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/MoveInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/StayInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/request/AccommodationInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/request/MoveInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/request/StayInfoRequest.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/response/AccommodationInfoResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/response/MoveInfoResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/dto/response/StayInfoResponse.java
  src/main/java/com/kdt_y_be_toy_project2/domain/itinerary/service/ItineraryService.java
  src/main/java/com/kdt_y_be_toy_project2/domain/trip/domain/Trip.java
  src/main/java/com/kdt_y_be_toy_project2/global/factory/DateScheduleInfoTestFactory.java
  src/main/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java
  src/main/java/com/kdt_y_be_toy_project2/global/util/LocalDateTimeUtil.java
  src/main/resources/application.yaml
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/DateScheduleInfoTestFactory.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/DateTimeScheduleInfoTestFactory.java
  src/test/java/com/kdt_y_be_toy_project2/global/factory/ItineraryFactory.java
Labels: docs, feat, test

#75 [fix] applicaiton.yaml 수정 및 profiles 파일 추가
  src/main/resources/application-dev.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
Labels: fix

#77 [test] 여행과 여정 통합 테스트
  src/main/java/com/kdt_y_be_toy_project2/global/error/ErrorCode.java
  src/main/java/com/kdt_y_be_toy_project2/global/factory/DateScheduleInfoTestFactory.java
  src/main/java/com/kdt_y_be_toy_project2/global/factory/TripTestFactory.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
  src/test/java/com/kdt_y_be_toy_project2/domain/itinerary/controller/ItineraryControllerTest.java
  src/test/java/com/kdt_y_be_toy_project2/integration/TripAndItineraryIntegrationTest.java
Labels: test

#74 [docs] README 작성
  docs/CODE_CONVENTION.md
  docs/GIT_CONVENTION.md
  docs/RUNNING_SCREEN.md
  docs/images/branch_strategy.png
  docs/images/commit_convention.png
  docs/images/erd.png
  docs/images/erd_class_diagram.png
  docs/images/postman/itinerary_create.png
  docs/images/postman/itinerary_edit.png
  docs/images/postman/itinerary_get.png
  docs/images/postman/itinerary_get_list.png
  docs/images/postman/trip_create.png
  docs/images/postman/trip_edit.png
  docs/images/postman/trip_get.png
  docs/images/postman/trip_get_list.png
  docs/images/project_schedule.png
  docs/images/spring_server_running_screen.png
  readme.md
Labels: docs
